# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

$schema: http://azureml/sdk-2-0/CommandComponent.json
name: microsoft.com.azureml.test.integrated_freeform2_lightGBM_train
version: 0.0.1
display_name: Integrated FreeForm2 lightGBM Train
type: CommandComponent
description: Train with lightGBM feature transformation binding.
tags: {}
inputs: 
  train_data_path:
    type: path
    description: The file path for the training data.
  parser_config_path:
    type: path
    description: The json path for parser config.
  label:
    type: string
    description: label column name
outputs: 
  model_path:
    type: path
    description: The output file path for the trained LightGBM model.
command: >-
  python train.py --train-data-path {inputs.train_data_path} --parser-config-path {inputs.parser_config_path} --label {inputs.label} --model-path {outputs.model_path}
environment:
  docker:
    image: docker.io/krystal1130/lightgbm_transform_dependencies:20211109.v1
  conda:
    conda_dependencies:
      name: project_environment
      channels:
      - defaults
      dependencies:
      - python=3.8
      - pip=20.0
      - pip:
        - lightgbm-transform==3.3.1 
  os: Linux
